# Generated by Django 4.0.4 on 2022-12-19 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('is_publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('is_publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('parent_id', models.BigIntegerField(default=0)),
                ('is_show', models.BooleanField(default=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('access', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('is_publish', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.area')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('is_publish', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.city')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='events_images')),
                ('is_show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('is_publish', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.district')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('house', models.CharField(max_length=10)),
                ('office', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_reserve', models.BooleanField(default=False)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.street')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main_photo', models.ImageField(upload_to='main_events_images')),
                ('contacts', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_show', models.BooleanField(default=True)),
                ('value', models.JSONField()),
                ('price', models.CharField(max_length=20)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.age')),
                ('category', models.ManyToManyField(blank=True, related_name='recipes', to='events.category')),
                ('photo', models.ManyToManyField(blank=True, related_name='recipes', to='events.photo')),
                ('type_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.typeevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('parent_id', models.BigIntegerField(default=0)),
                ('is_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='type_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.typecity'),
        ),
    ]
