# Generated by Django 4.0.4 on 2023-12-14 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_comment_updated_at_alter_event_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name_plural': 'Возраст'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Область'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Населенный пункт'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Комментарии мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'Район'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Мероприятие'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name_plural': 'Улица'},
        ),
        migrations.AlterModelOptions(
            name='typecity',
            options={'verbose_name_plural': 'Тип населенного пункта'},
        ),
        migrations.AlterModelOptions(
            name='typeevent',
            options={'verbose_name_plural': 'Тип мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name_plural': 'Место проведения'},
        ),
        migrations.AddField(
            model_name='event',
            name='start_event',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_event', to='events.event'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_event_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, to='events.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_photo',
            field=models.ImageField(upload_to='main_events_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ManyToManyField(blank=True, to='events.photo'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, to='events.venue'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to='events_images/'),
        ),
    ]
