version: "3.9"
services:
  postgres:
    container_name: pg_django_trpo
    image: postgres
    environment:
      POSTGRES_DB: "leisure"
      POSTGRES_USER: "raphael"
      POSTGRES_PASSWORD: "pg123ad32j5g34a"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raphael -d leisure"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_django_trpo
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "default@def.com"
      PGADMIN_DEFAULT_PASSWORD: "pg123ad32j5g34a"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    #volumes:
    #  - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge