# Generated by Django 4.0.4 on 2023-12-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_age_options_alter_area_options_and_more'),
        ('news', '0002_alter_comment_updated_at_alter_news_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Комментарии новостей'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='small_photo',
            field=models.ImageField(default='def.png', upload_to='small_news_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_news', to='news.news'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='newsCat', to='events.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_photo',
            field=models.ImageField(upload_to='main_news_images/'),
        ),
    ]
