# Generated by Django 4.0.4 on 2022-12-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
